python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1347
python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1348
python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1349
python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1350
python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1351
python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1352
python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1353
python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1355
python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1355
python bert.py ../../../data/all_revised_data/train.csv  bert --criterion auc_macro --seed 1356
